export interface Vibe {
  id: string;
  name: string;
  emoji: string;
  category: "dark" | "neon" | "minimal" | "warm" | "pastel" | "bold" | "chaos";
  previewBg: string;
  previewAccent: string;
  config: {
    background_override?: string | null;
    accent_color?: string;
    card_style?: "none" | "glass" | "solid" | "outlined" | "image";
    card_bg_override?: string;
    card_text_override?: string;
    card_bg_opacity?: number;
    card_blur?: number;
    card_border_radius?: number;
    card_shadow?: boolean;
    button_shape?: string;
    button_hover_effect?: string;
    button_style?: "rounded" | "pill" | "sharp";
    animation_type?: "none" | "gradient" | "particles" | "float";
    font_heading?: string;
    font_body?: string;
    font_buttons?: string;
    texture_type?: string;
    texture_opacity?: number;
    avatar_ring_style?: string;
    avatar_ring_color?: string;
    avatar_effect?: string;
    bg_overlay_opacity?: number;
    vibe_id?: string;
  };
}

export const VIBES: Vibe[] = [
  // ── DARK & MOODY ──
  {
    id: "midnight-chrome",
    name: "Midnight Chrome",
    emoji: "🌑",
    category: "dark",
    previewBg: "linear-gradient(180deg, #0a0a0f 0%, #141420 100%)",
    previewAccent: "#CBD5E1",
    config: {
      background_override: "linear-gradient(180deg, #0a0a0f 0%, #141420 100%)",
      accent_color: "#CBD5E1",
      card_style: "glass",
      card_bg_opacity: 40,
      card_blur: 20,
      card_border_radius: 16,
      button_shape: "sharp",
      button_hover_effect: "glow",
      animation_type: "none",
      font_heading: "Space Grotesk",
      avatar_ring_style: "solid",
      avatar_ring_color: "#CBD5E1",
    },
  },
  {
    id: "void",
    name: "Void",
    emoji: "🕳️",
    category: "dark",
    previewBg: "#000000",
    previewAccent: "#7C3AED",
    config: {
      background_override: "#000000",
      accent_color: "#7C3AED",
      card_style: "none",
      button_shape: "pill",
      button_hover_effect: "glow",
      animation_type: "particles",
      font_heading: "Syne",
      avatar_ring_style: "glow",
      avatar_ring_color: "#7C3AED",
      avatar_effect: "pulse",
    },
  },
  {
    id: "dark-academia",
    name: "Dark Academia",
    emoji: "📚",
    category: "dark",
    previewBg: "linear-gradient(135deg, #1a1208 0%, #2d1b0a 100%)",
    previewAccent: "#D97706",
    config: {
      background_override: "linear-gradient(135deg, #1a1208 0%, #2d1b0a 100%)",
      accent_color: "#D97706",
      card_style: "solid",
      card_bg_override: "#2d1b0a",
      card_bg_opacity: 80,
      card_border_radius: 8,
      button_shape: "rounded",
      button_hover_effect: "fill",
      font_heading: "Playfair Display",
      font_body: "DM Sans",
      texture_type: "grain",
      texture_opacity: 25,
    },
  },
  {
    id: "hacker",
    name: "Hacker",
    emoji: "💻",
    category: "dark",
    previewBg: "#001a00",
    previewAccent: "#00FF41",
    config: {
      background_override: "linear-gradient(180deg, #001a00 0%, #000d00 100%)",
      accent_color: "#00FF41",
      card_style: "outlined",
      card_bg_opacity: 100,
      card_border_radius: 4,
      button_shape: "sharp",
      button_hover_effect: "shimmer",
      font_heading: "JetBrains Mono",
      font_body: "JetBrains Mono",
      font_buttons: "JetBrains Mono",
      texture_type: "scanlines",
      texture_opacity: 15,
      animation_type: "particles",
    },
  },
  // ── NEON & ELECTRIC ──
  {
    id: "neon-tokyo",
    name: "Neon Tokyo",
    emoji: "🌸",
    category: "neon",
    previewBg: "linear-gradient(180deg, #020216 0%, #0a0428 100%)",
    previewAccent: "#FF0080",
    config: {
      background_override: "linear-gradient(180deg, #020216 0%, #0a0428 100%)",
      accent_color: "#FF0080",
      card_style: "glass",
      card_bg_opacity: 30,
      card_blur: 16,
      card_border_radius: 16,
      button_shape: "pill",
      button_hover_effect: "glow",
      animation_type: "particles",
      font_heading: "Orbitron",
      avatar_ring_style: "glow",
      avatar_ring_color: "#FF0080",
      avatar_effect: "glow",
    },
  },
  {
    id: "electric-violet",
    name: "Electric Violet",
    emoji: "⚡",
    category: "neon",
    previewBg: "linear-gradient(135deg, #1a0533 0%, #0d0128 100%)",
    previewAccent: "#8B5CF6",
    config: {
      background_override: "linear-gradient(135deg, #1a0533 0%, #0d0128 50%, #0a0020 100%)",
      accent_color: "#8B5CF6",
      card_style: "glass",
      card_bg_opacity: 35,
      card_blur: 24,
      card_border_radius: 20,
      button_shape: "pill",
      button_hover_effect: "lift",
      animation_type: "gradient",
      avatar_ring_style: "rotating",
      avatar_ring_color: "#8B5CF6",
      avatar_effect: "float",
    },
  },
  {
    id: "synthwave",
    name: "Synthwave",
    emoji: "🌅",
    category: "neon",
    previewBg: "linear-gradient(180deg, #0d0221 0%, #1a0533 50%, #2d1b69 100%)",
    previewAccent: "#00FFFF",
    config: {
      background_override: "linear-gradient(180deg, #0d0221 0%, #1a0533 50%, #2d1b69 100%)",
      accent_color: "#00FFFF",
      card_style: "outlined",
      card_border_radius: 0,
      button_shape: "sharp",
      button_hover_effect: "shimmer",
      font_heading: "Orbitron",
      font_buttons: "Rajdhani",
      texture_type: "grid",
      texture_opacity: 10,
    },
  },
  {
    id: "cyber-pink",
    name: "Cyber Pink",
    emoji: "💖",
    category: "neon",
    previewBg: "linear-gradient(135deg, #1a001a 0%, #2d0028 100%)",
    previewAccent: "#EC4899",
    config: {
      background_override: "linear-gradient(135deg, #1a001a 0%, #2d0028 100%)",
      accent_color: "#EC4899",
      card_style: "glass",
      card_bg_opacity: 25,
      card_blur: 20,
      card_border_radius: 24,
      button_shape: "pill",
      button_hover_effect: "glow",
      animation_type: "float",
      font_heading: "Syne",
      avatar_ring_style: "gradient",
      avatar_ring_color: "#EC4899",
    },
  },
  // ── MINIMAL & CLEAN ──
  {
    id: "ghost",
    name: "Ghost",
    emoji: "👻",
    category: "minimal",
    previewBg: "#0a0a0a",
    previewAccent: "#ffffff",
    config: {
      background_override: "#0a0a0a",
      accent_color: "#ffffff",
      card_style: "none",
      button_shape: "rounded",
      button_hover_effect: "scale",
      font_heading: "DM Sans",
      animation_type: "none",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    emoji: "⬛",
    category: "minimal",
    previewBg: "#111111",
    previewAccent: "#f5f5f5",
    config: {
      background_override: "#111111",
      accent_color: "#f5f5f5",
      card_style: "outlined",
      card_border_radius: 0,
      button_shape: "sharp",
      button_hover_effect: "fill",
      font_heading: "Outfit",
      animation_type: "none",
    },
  },
  {
    id: "soft-blur",
    name: "Soft Blur",
    emoji: "🫧",
    category: "minimal",
    previewBg: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    previewAccent: "#a78bfa",
    config: {
      background_override: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
      accent_color: "#a78bfa",
      card_style: "glass",
      card_bg_opacity: 50,
      card_blur: 32,
      card_border_radius: 24,
      button_shape: "pill",
      button_hover_effect: "scale",
      font_heading: "Plus Jakarta Sans",
    },
  },
  // ── WARM & EARTHY ──
  {
    id: "sunset",
    name: "Sunset",
    emoji: "🌇",
    category: "warm",
    previewBg: "linear-gradient(135deg, #c44b4b 0%, #e8875a 50%, #f4c842 100%)",
    previewAccent: "#1a0a00",
    config: {
      background_override: "linear-gradient(135deg, #c44b4b 0%, #e8875a 50%, #f4c842 100%)",
      accent_color: "#1a0a00",
      card_style: "solid",
      card_bg_override: "#fff8f0",
      card_text_override: "#1a0a00",
      card_bg_opacity: 90,
      card_border_radius: 16,
      button_shape: "rounded",
      button_hover_effect: "lift",
      font_heading: "Playfair Display",
      animation_type: "gradient",
    },
  },
  {
    id: "terracotta",
    name: "Terracotta",
    emoji: "🏺",
    category: "warm",
    previewBg: "linear-gradient(180deg, #2d1b0e 0%, #3d2415 100%)",
    previewAccent: "#E07B54",
    config: {
      background_override: "linear-gradient(180deg, #2d1b0e 0%, #3d2415 100%)",
      accent_color: "#E07B54",
      card_style: "glass",
      card_bg_opacity: 30,
      card_blur: 12,
      card_border_radius: 12,
      button_shape: "rounded",
      button_hover_effect: "fill",
      font_heading: "DM Serif Display",
      texture_type: "grain",
      texture_opacity: 20,
    },
  },
  // ── PASTEL & SOFT ──
  {
    id: "dreamy",
    name: "Dreamy",
    emoji: "🌸",
    category: "pastel",
    previewBg: "linear-gradient(135deg, #667eea 0%, #f093fb 100%)",
    previewAccent: "#ffffff",
    config: {
      background_override: "linear-gradient(135deg, #667eea 0%, #f093fb 100%)",
      accent_color: "#ffffff",
      card_style: "glass",
      card_bg_opacity: 40,
      card_blur: 20,
      card_border_radius: 24,
      button_shape: "pill",
      button_hover_effect: "scale",
      font_heading: "Caveat",
      font_body: "DM Sans",
      animation_type: "gradient",
      avatar_effect: "float",
    },
  },
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    emoji: "🍬",
    category: "pastel",
    previewBg: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    previewAccent: "#d63384",
    config: {
      background_override: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
      accent_color: "#d63384",
      card_style: "glass",
      card_bg_opacity: 60,
      card_blur: 16,
      card_border_radius: 32,
      button_shape: "pill",
      button_hover_effect: "jelly",
      font_heading: "Pacifico",
      font_body: "DM Sans",
      animation_type: "float",
    },
  },
  // ── BOLD & LOUD ──
  {
    id: "fire",
    name: "Fire",
    emoji: "🔥",
    category: "bold",
    previewBg: "linear-gradient(135deg, #0d0000 0%, #1a0500 100%)",
    previewAccent: "#FF4500",
    config: {
      background_override: "linear-gradient(135deg, #0d0000 0%, #1a0500 100%)",
      accent_color: "#FF4500",
      card_style: "glass",
      card_bg_opacity: 25,
      card_blur: 10,
      card_border_radius: 8,
      button_shape: "sharp",
      button_hover_effect: "glow",
      animation_type: "particles",
      font_heading: "Archivo Black",
      avatar_ring_style: "glow",
      avatar_ring_color: "#FF4500",
      avatar_effect: "pulse",
    },
  },
  {
    id: "street",
    name: "Street",
    emoji: "🔤",
    category: "bold",
    previewBg: "#0a0a0a",
    previewAccent: "#FACC15",
    config: {
      background_override: "#0a0a0a",
      accent_color: "#FACC15",
      card_style: "none",
      button_shape: "sharp",
      button_hover_effect: "fill",
      font_heading: "Bebas Neue",
      font_buttons: "Bebas Neue",
      animation_type: "none",
    },
  },
  // ── GEN Z CHAOS ──
  {
    id: "cyber-noise",
    name: "Cyber Noise",
    emoji: "📺",
    category: "chaos",
    previewBg: "#0a0014",
    previewAccent: "#00FF41",
    config: {
      background_override: "#0a0014",
      accent_color: "#00FF41",
      card_style: "outlined",
      card_border_radius: 0,
      button_shape: "sharp",
      button_hover_effect: "shimmer",
      font_heading: "Orbitron",
      font_body: "JetBrains Mono",
      font_buttons: "JetBrains Mono",
      texture_type: "scanlines",
      texture_opacity: 20,
      animation_type: "particles",
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    emoji: "🌊",
    category: "chaos",
    previewBg: "linear-gradient(180deg, #0d0221 0%, #1a0a3d 40%, #2d1069 100%)",
    previewAccent: "#FF71CE",
    config: {
      background_override: "linear-gradient(180deg, #0d0221 0%, #1a0a3d 40%, #2d1069 100%)",
      accent_color: "#FF71CE",
      card_style: "glass",
      card_bg_opacity: 20,
      card_blur: 20,
      card_border_radius: 0,
      button_shape: "sharp",
      button_hover_effect: "glow",
      font_heading: "Orbitron",
      texture_type: "grid",
      texture_opacity: 15,
      animation_type: "gradient",
      avatar_ring_style: "gradient",
      avatar_ring_color: "#FF71CE",
    },
  },
  {
    id: "maximalist",
    name: "Maximalist",
    emoji: "🌈",
    category: "chaos",
    previewBg: "linear-gradient(135deg, #f953c6 0%, #b91d73 50%, #7c3aed 100%)",
    previewAccent: "#FACC15",
    config: {
      background_override: "linear-gradient(135deg, #f953c6 0%, #b91d73 50%, #7c3aed 100%)",
      accent_color: "#FACC15",
      card_style: "glass",
      card_bg_opacity: 35,
      card_blur: 16,
      card_border_radius: 32,
      button_shape: "pill",
      button_hover_effect: "jelly",
      font_heading: "Bebas Neue",
      font_body: "Outfit",
      animation_type: "gradient",
      avatar_ring_style: "rotating",
      avatar_ring_color: "#FACC15",
      avatar_effect: "float",
    },
  },
];

export const VIBE_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "dark", label: "Dark" },
  { id: "neon", label: "Neon" },
  { id: "minimal", label: "Minimal" },
  { id: "warm", label: "Warm" },
  { id: "pastel", label: "Pastel" },
  { id: "bold", label: "Bold" },
  { id: "chaos", label: "Gen Z" },
] as const;
